# Generated by Django 2.1.5 on 2019-01-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.RemoveField(
            model_name='var',
            name='site',
        ),
        migrations.DeleteModel(
            name='Var',
        ),
    ]
