# Generated by Django 2.1 on 2019-04-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_emailpush_linepush'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailpush',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
    ]
