# Generated by Django 2.1 on 2019-04-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190417_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linepush',
            name='user_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='ユーザーID'),
        ),
    ]
